# LabExercise Numpy Exercises

##### Ana Chaloska

## Array Calculations and Array Indexing

In [47]:
import numpy as np

In [145]:
A=np.array([1,2,3])
B=np.array([4,5,6])

#### 1.Given arrays A and B each of the same size calculate their sum (elementwise) and their product (elementwise)

In [63]:
print('The sum of A and B is',np.add(A,B),'.')
print('The product of A and B is',np.multiply(A,B),'.')

The sum of A and B is [5 7 9] .
The product of A and B is [ 4 10 18] .


#### 2.Calculate the mean of all elements in an array A without using the np.mean or np.average functions.

In [64]:
A_mean=np.sum(A)/np.size(A)
print('The mean of all elements in A is',A_mean,'.')

The mean of all elements in A is 2.0 .


#### 3.Calculate the standard deviation of all elements in an array A without using np.var or np.std.

In [65]:
A_std=np.sqrt(np.sum(np.square((A-A_mean)))/np.size(np.square((A-A_mean))))
print('The standard deviation of all elements in A is', A_std,'.')

The standard deviation of all elements in A is 0.816496580928 .


#### 4.Given an array C with shape (128,) calculate the sum of the first, third, fifth, etc elements (A[0]+A[2]+...).

In [284]:
C=np.random.rand(128) # Creates an array C with shape (128,)
D=np.tile((1,0), 64) # Creates an array [1 0 1 0 ...] with shape (128,0)
Even_index_sum=np.sum(np.multiply(C,D)) # Multiplies C and D (elementwise), so the odd-index elements become zeros, 
                                        # then sums up the elements of the product
print('The sum of the 1st, 3rd etc. elements in C is', Even_index_sum,'.')


The sum of the 1st, 3rd etc. elements in C is 28.7337576617 .


#### 5.Given an array E with shape (1024,) make an array F containing only the first 512 elements of E. I.e. F-shape should be (512,).


In [430]:
E=np.random.rand(1024) # Creates an array E with shape (1024,)
E_reshape=np.reshape(E, (2, 512)) # Reshapes E into an array with shape (2,512)
E_row1=E_reshape[0,:] # Selects the 1st row of E which includes the first 512 elements of E
print('The first 512 elements of E are:',"\n", E_row1)

The first 512 elements of E are: 
 [  8.59348187e-02   7.49364890e-01   2.73371871e-01   3.02963604e-01
   5.76152215e-01   8.62525898e-01   4.70522695e-01   9.17006811e-01
   8.23449744e-01   7.68516037e-01   5.54124227e-01   9.53600997e-01
   3.96670498e-01   3.38196897e-01   5.96744913e-01   6.57073520e-01
   2.97466763e-01   4.47917483e-01   1.49629636e-01   1.94097387e-01
   5.57683434e-02   9.76733473e-01   5.02638044e-01   8.63210559e-02
   2.02987086e-01   8.93840245e-02   1.48454579e-01   8.84098423e-01
   6.49634705e-01   8.22399454e-01   8.37766252e-01   9.31095725e-01
   7.76521654e-01   3.84936769e-01   4.62517747e-01   9.22410073e-01
   6.49057932e-01   3.46729042e-01   8.02930427e-01   1.44436001e-01
   4.01542474e-01   5.66831916e-01   8.64666473e-01   5.30811195e-01
   8.28836427e-01   2.56611280e-01   7.02808972e-01   1.75505569e-01
   1.86265932e-01   5.23475658e-01   7.47140837e-01   9.13037797e-01
   7.98312728e-01   6.65873505e-01   8.20101964e-02   7.56326195e-01

#### 6.Given an array F with shape (1024,) make an array G containing only the elements F[22],F[23],...,F[42].

In [192]:
F=np.random.rand(1024) # Creates an array F with shape (1024,)
G=F[22:43] # Creates array with elements F[22], F[23], ... F[42]
print(G) # Prints array G

[ 0.81456212  0.39554759  0.484383    0.13873475  0.78415574  0.65188356
  0.40596577  0.97121611  0.62576593  0.31612143  0.08757549  0.99255293
  0.05814735  0.5554487   0.46372684  0.47995663  0.52374162  0.66350454
  0.63612158  0.69467363  0.95102811]


#### 7.Given an array H with shape (1024,) and an integer array I make an array J whose elements are H[I[0]], H[I[1]], ..., H[I[-1]]

In [279]:
H=np.random.rand(1024) # Creates an array H with shape (1024,)
I=np.random.randint(1023, size=10) # Creates an array I whose elements are less than 1023=1024-1 (because of 0 based indexing)
J=H[I] # Creates an array J whose elements are H[I[0]], H[I[1]], ..., H[I[-1]]
print(J) # Prints array J

[ 0.36108955  0.17375816  0.38413165  0.61212246  0.80551296  0.18991923
  0.71442242  0.21721641  0.48091425  0.77258173]


#### 8.Given an array K with shape (L,) make an array with all elements of K in reverse order.

In [318]:
L=10 # Defines the value of L
K=np.random.rand(10) # Creates an array K with shape (L,)
K_reverse=np.flip(K,0) # Creates an array with all elements in K in reverse order
print(K_reverse) # Prints the array

[ 0.18188466  0.33714675  0.20533481  0.08305018  0.44686847  0.78460559
  0.61417077  0.37305794  0.76706254  0.55399902]


#### 9.Given an array M = np.random.rand(128) make an array N containing all elements in M that are less then or equal to 0.5

In [324]:
M = np.random.rand(128) # Creates an array M with shape (128,)
N=M[M<=0.5] # Creates an array N containing all elements in M that are less then or equal to 0.5
print(N) # Prints N

[ 0.42303242  0.24346565  0.1420092   0.01673722  0.01637905  0.25037336
  0.46947912  0.37489686  0.19365538  0.25273797  0.11816641  0.44329913
  0.05119372  0.40348029  0.11101847  0.0205364   0.37056514  0.23263462
  0.37350509  0.08450317  0.39673195  0.29424404  0.35120143  0.43354923
  0.28844632  0.27245552  0.08021493  0.16703516  0.03602797  0.01456486
  0.24663275  0.09578834  0.06088555  0.13978127  0.24331179  0.41517899
  0.28154134  0.28230684  0.41600097  0.39896061  0.25603338  0.2492781
  0.34839367  0.05983595  0.42462039  0.11544431  0.44015788  0.24997466
  0.31944968  0.08516607  0.45804951  0.34884688]


## Tricks with Arrays

#### 1.Given an array (vector) A of shape (N,) make it into an array B of shape (N,1).

In [369]:
N=9 # Defines a value for N
A=np.random.rand(N) # Creates an array A with shape (N,)
B=np.reshape(A, (N, 1)) # Cretaes an array B by reshaping A 
print(B.shape, "\n", B) # Prints B and its shape (N,1)

(9, 1) 
 [[ 0.50582306]
 [ 0.02383971]
 [ 0.26965435]
 [ 0.48968905]
 [ 0.42301984]
 [ 0.10712845]
 [ 0.00412713]
 [ 0.78668994]
 [ 0.27866335]]


#### 2.Given an array (vector) A of shape (N,) make it into an array B of shape (1,N).

In [384]:
N=9 # Defines a value for N
A=np.random.rand(N) # Creates an array A with shape (N,)
B=np.reshape(A, (1, N)) # Cretaes an array B by reshaping A 
print(B.shape, "\n", B) # Prints B and its shape (1,N)

(1, 9) 
 [[ 0.14366039  0.97644732  0.23797196  0.25962772  0.94279429  0.72647552
   0.71664643  0.11116799  0.75067731]]


#### 3.Given an array A of shape (M,N) what is A[i]? What are the valid values for i?

A[i] is the same as, A[i, :], meaning that it contains the elements of the row with index i in A. For instance, A[0] i the row with index 0. The values for i are 0,1,..,M-1.

#### 4.Let A35 be an array of shape (3,5) and let v5 be an array of shape (5,). Subtract v5 from each row in A35.

In [393]:
A35=np.random.rand(3,5) # Creates an array A35 with shape (3.5)
v5=np.random.rand(5) # Cretaes an array v5 with shape (5,)
Diff=A35-v5 # Performs subtraction of A35 and v5 via Broadcasting
print(Diff) # Prints the result of the subtraction

[[ 0.35609917  0.36720758  0.29906883  0.36681036  0.22934224]
 [ 0.65424076  0.13507459  0.75775083  0.0205594   0.21886645]
 [ 0.15971535 -0.17589283  0.48835588 -0.27972766  0.22049963]]


#### 5.Let A35 be an array of shape (3,5) and let v3 be an array of shape (3,). Subtract v3 from each column in A35.

In [406]:
A35=np.random.rand(3,5) # Creates an array A35 with shape (3.5)
v5=np.random.rand(3) # Cretaes an array v5 with shape (3,)
Diff=A35.T-v5 # Performs subtraction of A35 transpose and v5 via Broadcasting
print(Diff)

[[-0.18046863 -0.46604827 -0.18611295]
 [-0.77207453 -0.85436703  0.12153524]
 [-0.74507677 -0.17135359  0.15387632]
 [-0.0862131  -0.25885569 -0.63638839]
 [-0.53478727 -0.85034012 -0.60775419]]


## Linear Algebra

#### 1.Calculate the inner product of two vector v and w both of shape (N,).

In [410]:
N=9 # Defines a value for N
v=np.random.rand(N) # Creates a vector v with shape (N,)
w=np.random.rand(N) # Creates a vector w with shape (N,)
vw=v@w # Computes the inner (dot) product of v and w
print(vw) # Prints the result

2.04795895543


#### 2.Calculate the product of a matrix A of shape (M,N) with a vector v of shape (N,).

In [417]:
M=8 # Defines a value for M
N=9 # Defines a value for N
A=np.random.rand(M,N) # Creates a matrix A with shape (M,N)
v=np.random.rand(N) # Creates a vector v with shape (N,)
Av=A@v # Computes the inner (dot) product of A and v
print(Av) # Prints the result

[ 1.85634422  1.89516535  1.74687578  1.995466    1.20436891  1.76046446
  2.63124515  2.1441333 ]


#### 3.Let v be an array of shape (N,). What is the shape of v.T (or np.transpose(v))

The shape is unchanged: (N,). Here is an example for an array with shape (9,).

In [426]:
N=9 # Defines a value for N
v=np.random.rand(N) # Creates a vector v with shape (N,)
print(v.T.shape) # Prints the shape of the transpose of v

(9,)


#### 4.Let A be an array of shape (3,5) and let v3 be an array of shape (3,). We define v31 = v3.reshape(3,1). What is v3 @ A, v31 @ A and v31.T @ A?

In [429]:
A=np.random.rand(3,5)
v3=np.random.rand(3,)
v31 = v3.reshape(3,1)
print ('v3@A is', v3@A, '.')
print ('v31.T@A is', v31.T@A, '.')

v3@A is [ 1.49431418  1.16869589  1.0033789   1.54999043  0.97685315] .
v31.T@A is [[ 1.49431418  1.16869589  1.0033789   1.54999043  0.97685315]] .


v31@A cannot be computed because v31 has 1 column and A has 3 rows.